# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_14,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_14 ];
      }
      ''
        hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then
          rev_base
        else
          "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "dotenv-1.1.0-eyjU0Sk2AAAC8gbGBRVJBMO_2pVHeh3EJLbZrO3GGwQ-";
    path = fetchZigArtifact {
      name = "dotenv";
      url = "git+https://github.com/pandadiestro/dotenv.zig.git#b0f946e9c06879558ccfd0603e3daaa56b6c2739";
      hash = "sha256-JPurxExhGXIALJeS4l5upLrCBPGJmpVa0WKJjwOeO8g=";
    };
  }
  {
    name = "libpq-5.16.4-QME6aVj4AAD9AxF3KV877U06maI3NcEjO_a9T8JJtOG9";
    path = fetchZigArtifact {
      name = "libpq";
      url = "git+https://github.com/allyourcodebase/libpq?ref=5.16.4+3#b8b3a5acc9d2613ab926e2f7625552bbf9acaf90";
      hash = "sha256-iToCHz7DiuO7k+dJKV9hS+jf+2hXsPKlPeRBEnTpomY=";
    };
  }
  {
    name = "libressl-4.0.0--kqV4LnSAACWhbUEm8O5KHGuJpNJsN0xLIlbFun7ql-m";
    path = fetchZigArtifact {
      name = "libressl";
      url = "git+https://github.com/allyourcodebase/libressl?ref=4.0.0+2#18d16b266328f3e568ab4ee614ae8c054b682c9e";
      hash = "sha256-fWD3sd/oHK5bsiJDL9rnGGFYHYOBIHUf1w2I3h6Drhw=";
    };
  }
  {
    name = "N-V-__8AAGvDTQHGV38aqRN9PCALgEg4_XExU4juxdTJMTVQ";
    path = fetchZigArtifact {
      name = "libressl";
      url = "https://github.com/libressl/portable/releases/download/v4.0.0/libressl-4.0.0.tar.gz";
      hash = "sha256-TYQZVfCsw9/HHQ49018oOvRhIiNQ4mhD/qlzHAJGoeQ=";
    };
  }
  {
    name = "openssl-3.3.1-2-TC9C3Se3ZACF5WO_CjoD7Bt_X94oCsAAbbwhOp1rTZBe";
    path = fetchZigArtifact {
      name = "openssl";
      url = "git+https://github.com/allyourcodebase/openssl?ref=main#f348124c5382bcc377f1b3277357cbf2ed2fb8db";
      hash = "sha256-3Bo8V2fXjqvqYOEjRjK4ZwvP76hndd3YYbqqznWfIZc=";
    };
  }
  {
    name = "N-V-__8AAIg12QPZxABEXJw-1G9x69vDZLezSUcyMYhML25U";
    path = fetchZigArtifact {
      name = "openssl";
      url = "https://github.com/openssl/openssl/releases/download/openssl-3.3.0/openssl-3.3.0.tar.gz";
      hash = "sha256-U+ZrBDMipgar8Ah+dpmg4DOjf6E/65dC3zXDozsY+wI=";
    };
  }
  {
    name = "N-V-__8AAKeztweKsqUQCZESI7M-Rw2v-1IU1bTHR5SS-px6";
    path = fetchZigArtifact {
      name = "upstream";
      url = "git+https://github.com/postgres/postgres?ref=REL_16_4#2caa85f4aae689e6f6721d7363b4c66a2a6417d6";
      hash = "sha256-Xrdb0byEPFO7fn5QPfWYn9EfGDLsXz7HRzL2RJrco74=";
    };
  }
  {
    name = "zlib-1.3.1-ZZQ7lVgMAACwO4nUUd8GLhsuQ5JQq_VAhlEiENJTUv6h";
    path = fetchZigArtifact {
      name = "zlib";
      url = "git+https://github.com/allyourcodebase/zlib?ref=main#6c72830882690c1eb2567a537525c3f432c1da50";
      hash = "sha256-JS1TM18BrN2sOI3sGv5j/hVm76kE+i4lSYBHy4wPTlY=";
    };
  }
  {
    name = "N-V-__8AAB0eQwD-0MdOEBmz7intriBReIsIDNlukNVoNu6o";
    path = fetchZigArtifact {
      name = "zlib";
      url = "https://github.com/madler/zlib/archive/refs/tags/v1.3.1.tar.gz";
      hash = "sha256-F+iIY/NgBnKrSRgvIXKBtvxNPHYr3jYZNeQ2qVIU0Fw=";
    };
  }
  {
    name = "zstd-1.5.7-KEItkJ8vAAC5_rRlKmLflYQ-eKXbAIQBWZNmmJtS18q0";
    path = fetchZigArtifact {
      name = "zstd";
      url = "git+https://github.com/allyourcodebase/zstd?ref=1.5.7#01327d49cbc56dc24c20a167bb0055d7fc23de84";
      hash = "sha256-1w+hR2U9t6R4sNvUMynDsYO0sNAan2svjxjUvxT+x6A=";
    };
  }
  {
    name = "N-V-__8AAGxifwAAGwXwvsnl_aOXFGLZTeYCu0WBhuEXr96u";
    path = fetchZigArtifact {
      name = "zstd";
      url = "git+https://github.com/facebook/zstd.git?ref=v1.5.7#f8745da6ff1ad1e7bab384bd1f9d742439278e99";
      hash = "sha256-tNFWIT9ydfozB8dWcmTMuZLCQmQudTFJIkSr0aG7S44=";
    };
  }
]
